name: and10
title: and10
description: 'Sometimes doing the wrong things for the right reasons'
author: and1zero
markdown: kramdown
permalinks:
  - /404.html
  - /blog/:year/:month/:day/:title
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
