# Site Info
title: and1zero
description: 'Lesson Learned and Personal Thoughts'
url: https://and1zero.github.io
logo: /public/logo.svg

# Site Configurations
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

# About/contact
author:
  name: Andi Susanto
  description: A curious person, always breaking things and try to fix them
  gravatar: 5e382ffbca80a385b3c7ef9917dfd9a2
  url: https://and1zero.github.io
  contact:
    linkedin: https://www.linkedin.com/in/andisusanto
    github: https://github.com/and1zero
    gitlab: https://gitlab.com/and1zero
    email: https://mailhide.io/e/oxS3l

# Custom vars
version: 1.0.0

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

# Plugins
mathjax: false # whether support mathjax
google_analytics_token: 'UA-36578544-2' # leave blank if you don't want google analytics
disqus_short_name: false # leave blank if you don't want disqus